name: tests
description: A Finance planner to keep control of budget.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.2
  charts_flutter: ^0.12.0
  syncfusion_flutter_charts: ^21.2.4
  flutter_neumorphic: ^3.2.0
  awesome_dialog: ^3.1.0
  easy_localization: ^3.0.2
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.0
  circular_seek_bar: ^1.1.0
  tab_indicator_styler: ^2.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "lib/assets/mfa_logo.png"
  android: true
  ios: true


flutter:

  uses-material-design: true

  assets:
    - lib/assets/translations/
    - lib/assets/savings_icon.svg
    - lib/assets/mfa_logo.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: lib/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: lib/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: lib/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: lib/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: lib/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: lib/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: lib/fonts/Montserrat-Thin.ttf
          weight: 100

